# Generated by Django 5.1.4 on 2025-08-04 17:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Plan name (e.g., 'Basic', 'Premium')", max_length=100
                    ),
                ),
                (
                    "slug",
                    models.SlugField(help_text="URL-friendly identifier", unique=True),
                ),
                (
                    "description",
                    models.TextField(help_text="Plan description and features"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly price in USD",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code (USD, EUR, etc.)",
                        max_length=3,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        help_text="Billing frequency",
                        max_length=20,
                    ),
                ),
                (
                    "max_recipes",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of recipes user can save (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "max_meal_plans",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of meal plans (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "ai_meal_planning",
                    models.BooleanField(
                        default=False, help_text="Access to AI-powered meal planning"
                    ),
                ),
                (
                    "nutrition_analytics",
                    models.BooleanField(
                        default=False,
                        help_text="Advanced nutrition analytics and insights",
                    ),
                ),
                (
                    "priority_support",
                    models.BooleanField(
                        default=False, help_text="Priority customer support"
                    ),
                ),
                (
                    "custom_goals",
                    models.BooleanField(
                        default=False, help_text="Custom nutrition goals and tracking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this plan is available for new subscriptions",
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(
                        default=False, help_text="Mark as popular/recommended plan"
                    ),
                ),
                (
                    "trial_days",
                    models.IntegerField(
                        default=0,
                        help_text="Number of free trial days",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(365),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "db_table": "subscription_plans",
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Feature name", max_length=100, unique=True
                    ),
                ),
                (
                    "slug",
                    models.SlugField(help_text="URL-friendly identifier", unique=True),
                ),
                ("description", models.TextField(help_text="Feature description")),
                (
                    "feature_type",
                    models.CharField(
                        choices=[
                            ("boolean", "Boolean (on/off)"),
                            ("numeric", "Numeric (with limits)"),
                            ("unlimited", "Unlimited"),
                        ],
                        default="boolean",
                        help_text="Type of feature",
                        max_length=20,
                    ),
                ),
                (
                    "default_value",
                    models.JSONField(
                        default=dict, help_text="Default value for this feature"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("core", "Core Features"),
                            ("analytics", "Analytics"),
                            ("planning", "Meal Planning"),
                            ("social", "Social Features"),
                            ("support", "Support"),
                        ],
                        default="core",
                        help_text="Feature category",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Feature",
                "verbose_name_plural": "Subscription Features",
                "db_table": "subscription_features",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("canceled", "Canceled"),
                            ("past_due", "Past Due"),
                            ("unpaid", "Unpaid"),
                            ("trialing", "Trialing"),
                            ("paused", "Paused"),
                        ],
                        default="active",
                        help_text="Current subscription status",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(help_text="When subscription started"),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When subscription ends (null = ongoing)",
                        null=True,
                    ),
                ),
                (
                    "trial_end",
                    models.DateTimeField(
                        blank=True, help_text="When trial period ends", null=True
                    ),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When subscription was canceled",
                        null=True,
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(help_text="Start of current billing period"),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(help_text="End of current billing period"),
                ),
                (
                    "cancel_at_period_end",
                    models.BooleanField(
                        default=False, help_text="Cancel at end of current period"
                    ),
                ),
                (
                    "external_subscription_id",
                    models.CharField(
                        blank=True,
                        help_text="External payment provider subscription ID",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "external_customer_id",
                    models.CharField(
                        blank=True,
                        help_text="External payment provider customer ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="Subscription plan",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscriptions.plan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this subscription",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "db_table": "subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", help_text="Payment currency", max_length=3
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        help_text="Payment status",
                        max_length=20,
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, help_text="When payment was completed", null=True
                    ),
                ),
                (
                    "external_payment_id",
                    models.CharField(
                        blank=True,
                        help_text="External payment provider payment ID",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "external_invoice_id",
                    models.CharField(
                        blank=True,
                        help_text="External payment provider invoice ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="Payment description", max_length=255
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional payment metadata",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        help_text="Subscription this payment is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "db_table": "subscription_payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "value",
                    models.JSONField(
                        default=dict, help_text="Feature value for this plan"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="Subscription plan",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_features",
                        to="subscriptions.plan",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        help_text="Feature",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_features",
                        to="subscriptions.subscriptionfeature",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan Feature",
                "verbose_name_plural": "Plan Features",
                "db_table": "plan_features",
                "unique_together": {("plan", "feature")},
            },
        ),
    ]
