# Generated by Django 5.1.4 on 2025-08-04 17:10

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="DietaryRestriction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("vegetarian", "Vegetarian"),
                            ("vegan", "Vegan"),
                            ("gluten_free", "Gluten-Free"),
                            ("dairy_free", "Dairy-Free"),
                            ("nut_free", "Nut-Free"),
                            ("egg_free", "Egg-Free"),
                            ("soy_free", "Soy-Free"),
                            ("keto", "Ketogenic"),
                            ("paleo", "Paleo"),
                            ("low_carb", "Low-Carb"),
                            ("low_sodium", "Low-Sodium"),
                            ("diabetic_friendly", "Diabetic-Friendly"),
                            ("halal", "Halal"),
                            ("kosher", "Kosher"),
                            ("other", "Other"),
                        ],
                        help_text="Type of dietary restriction or guideline",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name for display", max_length=50
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the dietary restriction",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
                "indexes": [
                    models.Index(fields=["name"], name="recipes_die_name_6de056_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("protein", "Protein"),
                            ("dairy", "Dairy"),
                            ("grains", "Grains"),
                            ("vegetables", "Vegetables"),
                            ("fruits", "Fruits"),
                            ("herbs_spices", "Herbs & Spices"),
                            ("oils_fats", "Oils & Fats"),
                            ("nuts_seeds", "Nuts & Seeds"),
                            ("sweeteners", "Sweeteners"),
                            ("beverages", "Beverages"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "calories_per_100g",
                    models.FloatField(
                        blank=True, help_text="Calories per 100 grams", null=True
                    ),
                ),
                (
                    "protein_per_100g",
                    models.FloatField(
                        blank=True,
                        help_text="Protein in grams per 100 grams",
                        null=True,
                    ),
                ),
                (
                    "carbohydrates_per_100g",
                    models.FloatField(
                        blank=True,
                        help_text="Total carbohydrates in grams per 100 grams",
                        null=True,
                    ),
                ),
                (
                    "fat_per_100g",
                    models.FloatField(
                        blank=True,
                        help_text="Total fat in grams per 100 grams",
                        null=True,
                    ),
                ),
                (
                    "fiber_per_100g",
                    models.FloatField(
                        blank=True,
                        help_text="Dietary fiber in grams per 100 grams",
                        null=True,
                    ),
                ),
                (
                    "sugar_per_100g",
                    models.FloatField(
                        blank=True,
                        help_text="Total sugars in grams per 100 grams",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="recipes_ing_name_164c6a_idx"),
                    models.Index(
                        fields=["category"], name="recipes_ing_categor_b99d8e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, null=True, unique=True)),
                ("source_url", models.URLField(max_length=500)),
                ("source_site", models.CharField(max_length=100)),
                ("image_url", models.URLField(max_length=500)),
                ("instructions", models.JSONField()),
                (
                    "preparation_time",
                    models.PositiveIntegerField(
                        blank=True, help_text="Preparation time in minutes", null=True
                    ),
                ),
                (
                    "cooking_time",
                    models.PositiveIntegerField(
                        blank=True, help_text="Cooking time in minutes", null=True
                    ),
                ),
                (
                    "servings",
                    models.PositiveIntegerField(
                        blank=True, help_text="Number of servings", null=True
                    ),
                ),
                (
                    "cuisine_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of cuisine (e.g., 'Italian', 'Mexican', 'Asian')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "rating",
                    models.FloatField(
                        blank=True,
                        help_text="Average rating (0-5 stars)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "review_count",
                    models.PositiveIntegerField(
                        blank=True, help_text="Number of reviews/ratings", null=True
                    ),
                ),
                (
                    "embedding",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=384
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["title"], name="recipes_rec_title_9ebae8_idx"),
                    models.Index(
                        fields=["source_site"], name="recipes_rec_source__d1e5f9_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="recipes_rec_created_a55f59_idx"
                    ),
                    models.Index(
                        fields=["rating"], name="recipes_rec_rating_e9153a_idx"
                    ),
                    models.Index(
                        fields=["cuisine_type"], name="recipes_rec_cuisine_1a0186_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RecipeNutrition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("calories", models.FloatField(help_text="Calories per serving")),
                ("protein", models.FloatField(help_text="Protein per serving")),
                (
                    "carbohydrates",
                    models.FloatField(help_text="Carbohydrates per serving"),
                ),
                ("fat", models.FloatField(help_text="Fat per serving")),
                ("fiber", models.FloatField(help_text="Fiber per serving")),
                ("sugar", models.FloatField(help_text="Sugar per serving")),
                ("sodium", models.FloatField(help_text="Sodium per serving")),
                (
                    "saturated_fat",
                    models.FloatField(help_text="Saturated fat per serving"),
                ),
                (
                    "monounsaturated_fat",
                    models.FloatField(help_text="Monounsaturated fat per serving"),
                ),
                (
                    "polyunsaturated_fat",
                    models.FloatField(help_text="Polyunsaturated fat per serving"),
                ),
                ("cholesterol", models.FloatField(help_text="Cholesterol per serving")),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="macro_nutrition",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RecipeTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_tags",
                        to="recipes.recipe",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_recipes",
                        to="recipes.tag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IngredientAllergen",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "allergen_name",
                    models.CharField(
                        choices=[
                            ("dairy", "Dairy"),
                            ("eggs", "Eggs"),
                            ("fish", "Fish"),
                            ("shellfish", "Shellfish"),
                            ("tree_nuts", "Tree Nuts"),
                            ("peanuts", "Peanuts"),
                            ("wheat", "Wheat"),
                            ("soybeans", "Soybeans"),
                            ("sesame", "Sesame"),
                            ("gluten", "Gluten"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergens",
                        to="recipes.ingredient",
                    ),
                ),
            ],
            options={
                "ordering": ["allergen_name"],
                "indexes": [
                    models.Index(
                        fields=["allergen_name"], name="recipes_ing_allerge_a76200_idx"
                    ),
                    models.Index(
                        fields=["ingredient", "allergen_name"],
                        name="recipes_ing_ingredi_57efaf_idx",
                    ),
                ],
                "unique_together": {("ingredient", "allergen_name")},
            },
        ),
        migrations.CreateModel(
            name="RecipeDietaryRestriction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=1.0,
                        help_text="Confidence level (0.0-1.0) for auto-detected restrictions",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dietary_restriction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restricted_recipes",
                        to="recipes.dietaryrestriction",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_dietary_restrictions",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["dietary_restriction__display_name"],
                "indexes": [
                    models.Index(
                        fields=["recipe", "dietary_restriction"],
                        name="recipes_rec_recipe__d18a88_idx",
                    ),
                    models.Index(
                        fields=["dietary_restriction"],
                        name="recipes_rec_dietary_5048e2_idx",
                    ),
                ],
                "unique_together": {("recipe", "dietary_restriction")},
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.FloatField(help_text="Quantity of ingredient needed"),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Unit of measurement (e.g., 'cups', 'grams', 'pieces')",
                        max_length=50,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about preparation or substitutions",
                        null=True,
                    ),
                ),
                (
                    "original_text",
                    models.TextField(
                        blank=True,
                        help_text="Original text of the ingredient",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_ingredients",
                        to="recipes.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_ingredients",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["recipe", "ingredient"],
                        name="recipes_rec_recipe__35afb1_idx",
                    )
                ],
                "unique_together": {("recipe", "ingredient")},
            },
        ),
        migrations.CreateModel(
            name="RecipeVector",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "embedding",
                    models.TextField(
                        help_text="JSON serialized vector embedding (placeholder for pgvector)"
                    ),
                ),
                (
                    "embedding_version",
                    models.CharField(
                        help_text="Version of the embedding model used", max_length=50
                    ),
                ),
                (
                    "recipe",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["embedding_version"],
                        name="recipes_rec_embeddi_828064_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="recipes_rec_created_e3c134_idx"
                    ),
                ],
            },
        ),
    ]
