# Generated by Django 5.1.4 on 2026-01-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="author",
            field=models.CharField(
                blank=True, help_text="Recipe author name", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="description",
            field=models.TextField(
                blank=True, help_text="Recipe description or summary", null=True
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="difficulty_level",
            field=models.CharField(
                blank=True,
                help_text="Recipe difficulty level",
                max_length=50,
                null=True,
            ),
        ),
    ]
