# Generated by Django 5.1.4 on 2026-01-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_recipe_author_recipe_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="quantity",
            field=models.FloatField(
                blank=True, help_text="Quantity of ingredient needed", null=True
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="unit",
            field=models.CharField(
                blank=True,
                help_text="Unit of measurement (e.g., 'cups', 'grams', 'pieces')",
                max_length=50,
                null=True,
            ),
        ),
    ]
